Open Blog/project/auth.py
from flask import Flask,Blueprint, render_template, request, redirect, url_for, session, current_app
from flask_mysqldb import MySQL
import MySQLdb.cursors
import re
import os
from PIL import Image
import io
from . import db

auth = Blueprint('auth', __name__)

@auth.route("/signup/" ,methods=['POST', 'GET'])
def signup():  
    msg = ''
    if request.method == 'POST' and 'name' in request.form and 'username' in request.form and 'profilepic' in request.form and 'mobile' in request.form and 'email' in request.form and 'password' in request.form and 'interest[]' in request.form:
        name = request.form['name']
        username = request.form['username']
        propic = request.form['profilepic']
        mobile = request.form['mobile']  
        email = request.form['email']
        password = request.form['password']
        interests = request.form['interest[]']      
        cursor = db.connection.cursor(MySQLdb.cursors.DictCursor)
        cursor.execute('SELECT * FROM users WHERE username = % s', (username, ))
        account = cursor.fetchone()
        if account:
            msg = 'Account already exists !'
        elif not re.match(r'[^@]+@[^@]+\.[^@]+', email):
            msg = 'Invalid email address !'
            
        elif not re.match(r'[A-Za-z0-9]+', username):
            msg = 'name must contain only characters and numbers !'
        else:
            cursor.execute('INSERT INTO users VALUES (NULL,% s, % s, % s, % s, % s, % s, %s)', (name, username, mobile, email, password, interests,propic, ))
            db.connection.commit()
            msg = 'You have successfully registered !'
    elif request.method == 'POST':
        msg = 'Please fill out the form !'
    return render_template('signup.html', msg = msg)

@auth.route("/login/" , methods =['GET', 'POST'])
def signin():
    msg = ''
    if request.method == 'POST' and 'username' in request.form and 'password' in request.form:
        username = request.form['username']
        password = request.form['password']
        cursor = db.connection.cursor(MySQLdb.cursors.DictCursor)
        cursor.execute('SELECT * FROM users WHERE username = % s AND password = % s', (username, password, ))
        account = cursor.fetchone()
        if account:
            session['loggedin'] = True
            session['id'] = account['id']
            session['name'] = account['name']
            msg = 'Logged in successfully !'
            return redirect(url_for('views.home'))
        else:
            msg = 'Incorrect username / password !'
    return render_template('login.html', msg = msg,)

@auth.route("/account/" ,methods=['POST', 'GET'])
def account(): 
    if 'loggedin' in session:
        cursor = db.connection.cursor(MySQLdb.cursors.DictCursor)
        cursor.execute('SELECT * FROM users WHERE id = % s', (session['id'], ))
        account = cursor.fetchone()    
        return render_template('account.html', account=account)
    return redirect(url_for('views.signin'))

@auth.route('/logout')
def logout():
   session.pop('loggedin', None)
   session.pop('id', None)
   session.pop('name', None)
   return redirect(url_for('views.home'))



Open Blog/project/views.py
from flask import Flask, Blueprint, render_template, request, redirect, url_for, session, current_app
from flask_mysqldb import MySQL
import MySQLdb.cursors
import re
import os
from PIL import Image
import io
from . import db

views = Blueprint('views', __name__)

@views.route("/")
def home():
    if 'loggedin' in session:
        cursor = db.connection.cursor(MySQLdb.cursors.DictCursor)
        cursor.execute('SELECT * FROM users WHERE id = % s', (session['id'], ))
        account = cursor.fetchone()
        interest=account['interests']
        cursor.execute('SELECT * FROM posts order by post_id desc') 
        posts = cursor.fetchall()  
        cursor.execute('SELECT * FROM posts where category=%s limit 5',(interest,)) 
        post = cursor.fetchall()
        return render_template('index.html', account=account, posts=posts,post=post)
    return redirect(url_for('auth.signin'))

@views.route("/category/<string:cat>")
def category(cat):
    if 'loggedin' in session:
        cursor = db.connection.cursor(MySQLdb.cursors.DictCursor)
        cursor.execute('SELECT * FROM users WHERE id = % s', (session['id'], ))
        account = cursor.fetchone()
        interest=account['interests']
        cursor.execute('SELECT * FROM posts where category=%s order by post_id desc',(cat,)) 
        posts = cursor.fetchall()  
        cursor.execute('SELECT * FROM posts where category=%s limit 5',(interest,)) 
        post = cursor.fetchall()
        return render_template('index.html', account=account, posts=posts,post=post)
    return redirect(url_for('auth.signin'))

@views.route("/sort/<string:sort>")
def sort(sort):
    if 'loggedin' in session:
        cursor = db.connection.cursor(MySQLdb.cursors.DictCursor)
        cursor.execute('SELECT * FROM users WHERE id = % s', (session['id'], ))
        account = cursor.fetchone()
        interest=account['interests']
        if sort=='asc':
            cursor.execute('SELECT * FROM posts order by post_id asc') 
            posts = cursor.fetchall() 
        elif sort=='desc':
            cursor.execute('SELECT * FROM posts order by post_id desc') 
            posts = cursor.fetchall() 
        
        cursor.execute('SELECT * FROM posts where category=%s limit 5',(interest,)) 
        post = cursor.fetchall()
        return render_template('index.html', account=account, posts=posts,post=post)
    return redirect(url_for('auth.signin'))

@views.route("/post/" ,methods=['GET', 'POST'])
def post():
    if request.method == 'POST' and 'coverimg' in request.form and 'title' in request.form and 'subtitle' in request.form and 'category' in request.form and 'content' in request.form:
        coverimg = request.form['coverimg']
        title = request.form['title']
        subtitle=request.form['subtitle']
        category=request.form['category']
        content = request.form['content']        
        cursor = db.connection.cursor(MySQLdb.cursors.DictCursor)
        cursor.execute('SELECT * FROM users WHERE id = % s', (session['id'], ))
        accounta = cursor.fetchone()
        aid = session['id']
        aname = session['name']
        cursor.execute('INSERT INTO posts VALUES (% s,% s, % s, % s,NULL, % s, % s,% s,curdate())', (aid, coverimg, title, content, subtitle, category,aname ))
        db.connection.commit()
        
    elif request.method == 'POST':
        msg = 'Please fill out the form !'
   
    if 'loggedin' in session:
        cursor = db.connection.cursor(MySQLdb.cursors.DictCursor)
        cursor.execute('SELECT * FROM users WHERE id = % s', (session['id'], ))
        account = cursor.fetchone()    
        return render_template('post.html', account=account)
    return redirect(url_for('signin'))


@views.route("/mypost/")
def mypost():
    if 'loggedin' in session:
        cursor = db.connection.cursor(MySQLdb.cursors.DictCursor)
        cursor.execute('SELECT * FROM users WHERE id = % s', (session['id'], ))
        account = cursor.fetchone()   
        cursor.execute('select * from posts where user_id =% s', (session['id'],)) 
        mypost=cursor.fetchall()
        return render_template('mypost.html', account=account, mypost=mypost)
    return redirect(url_for('auth.signin'))



@views.route("/viewpost/<int:p_id>", methods=['GET', 'POST'])
def viewpost(p_id):    
    if 'loggedin' in session:
        cursor = db.connection.cursor(MySQLdb.cursors.DictCursor)
        cursor.execute('SELECT * FROM users WHERE id = % s', (session['id'], ))
        account = cursor.fetchone()
        cursor.execute('SELECT * FROM posts WHERE post_id = %s', (p_id,))    
        post = cursor.fetchone()
        cont = post['content'].replace('\n', '<br>')
        return render_template('viewpost.html', account=account, post=post, cont=cont)
    
    if request.method == 'POST':
        if request.form['delpos'] == 'dele':
            cursor = db.connection.cursor(MySQLdb.cursors.DictCursor)
            cursor.execute('delete from posts where post_id = % s', (p_id, ))       
    return redirect(url_for('auth.signin'))

@views.route("/delpos/<int:p_id>", methods=['post','get'])  
def delpos(p_id):    
    cursor = db.connection.cursor(MySQLdb.cursors.DictCursor)
    cursor.execute('delete from posts where post_id = % s', (p_id, ))
    db.connection.commit()
    return redirect(url_for('views.mypost'))

@views.route("/delfav/<int:p_id>", methods=['post','get'])  
def delfav(p_id):    
    cursor = db.connection.cursor(MySQLdb.cursors.DictCursor)
    cursor.execute('delete from favorites where (post_id = % s) and (user_id= %s)', (p_id, session['id'] ),)
    db.connection.commit()
    return redirect(url_for('views.favorites'))

@views.route("/update/<int:p_id>", methods=['post','get'])  
def update(p_id):    
    if request.method == 'POST' and 'coverimg' in request.form and  'title' in request.form and 'subtitle' in request.form and 'category' in request.form and 'content' in request.form:
        coverimg = request.form['coverimg']
        title = request.form['title']
        subtitle=request.form['subtitle']
        category=request.form['category']
        content = request.form['content']   
        aid = session['id']
        aname = session['name']
        cursor = db.connection.cursor(MySQLdb.cursors.DictCursor)
        cursor.execute('select coverpic from posts where post_id=%s',(p_id,))
        posts=cursor.fetchone()  
        cp=posts['coverpic']
        if coverimg:          
            cursor.execute('update posts set user_id=%s, coverpic=%s, title=%s, content=%s, post_id=%s, subtitle=%s, category=%s, aname=%s, post_date=curdate() where post_id=%s', (aid,coverimg, title, content, p_id, subtitle, category,aname, p_id ))
        else:   
            coverimg=cp 
            cursor.execute('update posts set user_id=%s, coverpic=%s, title=%s, content=%s, post_id=%s, subtitle=%s, category=%s, aname=%s, post_date=curdate() where post_id=%s', (aid,coverimg, title, content, p_id, subtitle, category,aname, p_id ))
        db.connection.commit()

    return redirect(url_for('views.mypost'))

@views.route("/edit_post/<int:p_id>", methods=['post','get'])  
def edit_post(p_id):    
    if 'loggedin' in session:
        cursor = db.connection.cursor(MySQLdb.cursors.DictCursor)
        cursor.execute('SELECT * FROM users WHERE id = % s', (session['id'], ))
        account = cursor.fetchone()
        cursor.execute('SELECT * FROM posts WHERE post_id = %s', (p_id,))    
        post = cursor.fetchone()        
        return render_template('edit_post.html',account=account, post=post)

    

@views.route("/add_favorites/<int:p_id>", methods=['post','get'])
def add_favorites(p_id):
    if 'loggedin' in session:
        cursor = db.connection.cursor(MySQLdb.cursors.DictCursor)
        cursor.execute('SELECT * FROM users WHERE id = % s', (session['id'], ))
        account = cursor.fetchone()
        cursor.execute('select * from posts where post_id=%s',(p_id,))
        posts=cursor.fetchone()
        title= posts['title']
        content= posts['content']
        aname= posts['aname']
        date= posts['post_date']
        coverpic=posts['coverpic']
        cursor.execute('insert into favorites values (NULL, %s, %s,%s,%s,%s,%s,%s)',(session['id'],p_id,title,content,aname,date,coverpic,))    
        post = cursor.fetchone()        
        db.connection.commit()
        return redirect(url_for('views.favorites'))
    
@views.route("/favorites/", methods=['post','get'])
def favorites():
    if 'loggedin' in session:
        cursor = db.connection.cursor(MySQLdb.cursors.DictCursor)
        cursor.execute('SELECT * FROM users WHERE id = % s', (session['id'], ))
        account = cursor.fetchone()     
        cursor.execute('select * from favorites where user_id = %s', (session['id'], ))   
        favpost=cursor.fetchall()
        db.connection.commit()
    return render_template('favorites.html', account=account, favpost=favpost)

@views.route("/authors/")
def authors():
    if 'loggedin' in session:
        cursor = db.connection.cursor(MySQLdb.cursors.DictCursor)
        cursor.execute('SELECT * FROM users WHERE id = % s', (session['id'], ))
        account = cursor.fetchone() 
        cursor.execute('select name,mobile,email,profilepic from users')
        authors = cursor.fetchall()   
        return render_template('authors.html', account=account, authors=authors)
    return redirect(url_for('signin'))

@views.route("/update_ac/", methods=['post','get'])  
def update_ac():    
    if request.method == 'POST' and 'name' in request.form and 'profilepic' in request.form and 'mobile' in request.form and 'email' in request.form and 'password' in request.form:
        name = request.form['name']
        profilepic=request.form['profilepic']

Open Blog/project/templates/about.html
{% extends "base.html" %}
{% block content %}
<!--Main Context Area-->
<div class="container" style="margin-right: 290px;"><br>
<h3>About Us</h3><br>
<div class="about-body">
<h4>Hello,</h4>
<p>Open Blog is social platform for create wonderful blogs. Here you can find lots of awesome blogs ,that helps you to increase your reading habit and improve your knowledge. </p>

     <p > Once a blog is indexed in search engines it stays there, meaning your blog can still gain traffic and generate leads weeks, months and even years after. Don’t look for instant leads and hundreds of views, give your blog time to generate interest. Blog topics that are timeless will constantly generate more views month after month, so make sure to write about topics you know will be of interest to your target audience.</p>
      
     
      <p>Blogging allows you to share information about your business and its services but it also allows you to share opinions and thoughts on certain topics.  Blogging is a great way to create a personality for your company and makes your business more credible approachable. So, don’t be afraid to share your interests on your blogs, comment on timely news topics or market trends or educate your readers on a particular topic. Always be sure you write blogs with your audience in mind.</p>

      <center> <a><svg class="bi me-2" width="22" height="22"><use xlink:href="#fb"/></svg></a>
            <a><svg class="bi me-2" width="22" height="22"><use xlink:href="#insta"/></svg></a>
            <a><svg class="bi me-2" width="22" height="22"><use xlink:href="#twitter"/></svg></a></center>
</div>
</div>
{% endblock %}

Open Blog/project/templates/edit_post.html
{% extends "base.html" %}
{% block content %}
<!--Main Context Area-->
<link href="../static/clean-blog.min.css" rel="stylesheet">
<div class="container"><br>
    <form action="{{ url_for('views.update', p_id = post.post_id ) }}" method="POST">
    <h3>Edit Post</h3><br>
  
    <div class="banner mb-6">
        <input type="file" name="coverimg" accept="image/*" id="banner-upload" onchange="loadFile(event);" hidden>
        <img id="output" src="../static/image/{{post.coverpic}}" alt="" class="cimg" >
        <label for="banner-upload" class="banner-upload-btn"><img src="../static/pics/upload.png" alt="upload banner"></label>
    </div>
    <br><br>
    <!--<div class="control-group">
      <div class="form-group floating-label-form-group controls">
        <label>Cover Image</label>
        <input type="text" class="form-control disabled" name="coverimg" placeholder="Cover Image" value="{{post.coverpic}}" id="title" >
        <p class="help-block text-danger"></p>
      </div>
    </div>-->
    <div class="control-group">
        <div class="form-group floating-label-form-group controls">
          <label>Title</label>
          <input type="text" class="form-control" placeholder="Title" value="{{post.title}}" name="title" id="title" required data-validation-required-message="Please enter a title.">
          <p class="help-block text-danger"></p>
        </div>
      </div>
      <div class="control-group">
        <div class="form-group floating-label-form-group controls">
          <label>Subtitle</label>
          <input type="text" class="form-control" placeholder="Subtitle" value="{{post.subtitle}}" name="subtitle" id="subtitle" required data-validation-required-message="Please enter your email address.">
          <p class="help-block text-danger"></p>
        </div>
      </div>

      <div class="control-group">
        <div class="form-group col-xs-12 floating-label-form-group controls">
          <label>Category</label>
      <select class="form-select form-control" value="{{post.category}}" aria-label="Default select example" name="category" style="color: #777;">
        <option selected value="{{post.category}}">{{post.category}}</option>
        <option value="Technology" >Technology</option>
        <option value="Entertainment" >Entertainment</option>
        <option value="Sports" >Sports</option>
        <option value="Economy" >Economy</option>
        <option value="Politics" >Politics</option>
        <option value="Lifestyle" >Life Style</option>
        <option value="Science" >Science</option>
      </select>
      <p class="help-block text-danger"></p>
    </div></div>


      <div class="control-group">
        <div class="form-group floating-label-form-group controls">
          <label>Content</label>
          <textarea rows="12" class="form-control" placeholder="Content" value="" name="content" id="content" required data-validation-required-message="Please enter a message.">{{post.content}}</textarea>
</div></div>
    <button class="btn pbtn text-white" type="submit">Update</button>
    <button class="btn btn-secondary" type="clear">Clear</button>

</form>

</div>
<div class="rbar">
  <div class="d-flex flex-column flex-shrink-0 p-3 " style="width: 280px;">


    <h4 style=" margin-bottom:-8px;">Categories</h4>
    <hr style="max-width: 250px;">

    <div class="list-group">
      <a href="{{ url_for('views.category',cat = 'Technology') }}" class=" cat-1 list-group-item list-group-item-action d-flex justify-content-between align-items-center" category-one="Technology">Technology
        <span class="badge rounded-pill">14</span>
      </a>
      <a href="{{ url_for('views.category',cat = 'Entertainment') }}" class=" cat-2 list-group-item list-group-item-action d-flex justify-content-between align-items-center" category-one="Entertainment">Entertainment
        <span class="badge rounded-pill">14</span>
      </a>
      <a href="{{ url_for('views.category',cat = 'Sports') }}" class=" cat-3 list-group-item list-group-item-action d-flex justify-content-between align-items-center">Sports
        <span class="badge rounded-pill">14</span>
      </a>
      <a href="{{ url_for('views.category',cat = 'Economy') }}" class=" cat-4 list-group-item list-group-item-action d-flex justify-content-between align-items-center">Economy
        <span class="badge rounded-pill">14</span>
      </a>
      <a href="{{ url_for('views.category',cat = 'Politics') }}" class="cat-5 list-group-item list-group-item-action d-flex justify-content-between align-items-center">Politics
        <span class="badge rounded-pill">14</span>
      </a>
      <a href="{{ url_for('views.category',cat = 'Lifestyle') }}" class="cat-6 list-group-item list-group-item-action d-flex justify-content-between align-items-center">Life Style
        <span class="badge rounded-pill">14</span>
      </a>
      <a href="{{ url_for('views.category',cat = 'Science') }}" class="cat-7 list-group-item list-group-item-action d-flex justify-content-between align-items-center">Science
        <span class="badge rounded-pill">14</span>
      </a>
    </div>
    </div>
<script>
    var loadFile = function(event) {
        var output = document.getElementById('output');
        output.src = URL.createObjectURL(event.target.files[0]);
        output.onload = function() {
          URL.revokeObjectURL(output.src) // free memory
        }
      };
</script>


{% endblock %}

Open Blog/project/templates/favorites.html
{% extends "base.html" %}
{% block content %}
<!--Main Context Area-->
<div class="container"><br>
<h3>Favorites</h3><br>
<div class="row row-cols-1 row-cols-md-2 g-4" id="myItems">
  {%for fav in favpost%}
  <div class="col">
    <a href="{{ url_for('views.viewpost', p_id = fav.post_id) }}">
      <div class="card">
      <div class="img-hover-zoom">
      <img src="../static/image/{{fav.coverpic}}" href="#" class="card-img-top" style="z-index: -1;"></div></a>        
      <div class="card-body bg-white" style="z-index:1; margin-top:-100px;">
        <p class="card-text aname mb-1"><small class="text-muted"><i class="fa fa-user"></i>&nbsp;{{fav.aname}}&nbsp;&nbsp;<i class="fa fa-calendar"></i>&nbsp;{{fav.post_date}}</small></p>
        <h5 class="card-title ctitle" >{{fav.title}}</h5>
        <p class="card-text cont">{{fav.content}}</p>
        
        
        <a href="{{ url_for('views.delfav',p_id = fav.post_id) }}" id=test onclick="return myFunction()"><button  class='btn btn-sm btn-danger' name="delpos">Remove</button></a>

        
      </div>
    </div>
  </div>
    {%endfor%}
    </div>
</div>
<div class="rbar">
  <div class="d-flex flex-column flex-shrink-0 p-3 " style="width: 280px;">


    <h4 style=" margin-bottom:-8px;">Categories</h4>
    <hr style="max-width: 250px;">

    <div class="list-group">
      <a href="{{ url_for('views.category',cat = 'Technology') }}" class=" cat-1 list-group-item list-group-item-action d-flex justify-content-between align-items-center" category-one="Technology">Technology
        <span class="badge rounded-pill">14</span>
      </a>
      <a href="{{ url_for('views.category',cat = 'Entertainment') }}" class=" cat-2 list-group-item list-group-item-action d-flex justify-content-between align-items-center" category-one="Entertainment">Entertainment
        <span class="badge rounded-pill">14</span>
      </a>
      <a href="{{ url_for('views.category',cat = 'Sports') }}" class=" cat-3 list-group-item list-group-item-action d-flex justify-content-between align-items-center">Sports
        <span class="badge rounded-pill">14</span>
      </a>
      <a href="{{ url_for('views.category',cat = 'Economy') }}" class=" cat-4 list-group-item list-group-item-action d-flex justify-content-between align-items-center">Economy
        <span class="badge rounded-pill">14</span>
      </a>
      <a href="{{ url_for('views.category',cat = 'Politics') }}" class="cat-5 list-group-item list-group-item-action d-flex justify-content-between align-items-center">Politics
        <span class="badge rounded-pill">14</span>
      </a>
      <a href="{{ url_for('views.category',cat = 'Lifestyle') }}" class="cat-6 list-group-item list-group-item-action d-flex justify-content-between align-items-center">Life Style
        <span class="badge rounded-pill">14</span>
      </a>
      <a href="{{ url_for('views.category',cat = 'Science') }}" class="cat-7 list-group-item list-group-item-action d-flex justify-content-between align-items-center">Science
        <span class="badge rounded-pill">14</span>
      </a>
    </div>
    </div>


<script>
  function myFunction() {
    if(confirm("Are you sure to delete this post!")) {

    }else{
      return false;
    }
  }
</script>
<script>
  function search() {
    var input, filter, cards, cardContainer, h5,p, title,content,aname, i;
    input = document.getElementById("searchbar");
    filter = input.value.toUpperCase();
    cardContainer = document.getElementById("myItems");
    cards = cardContainer.getElementsByClassName("col");
    for (i = 0; i < cards.length; i++) {
        title = cards[i].querySelector(".card-body h5.card-title");
        content = cards[i].querySelector(".card-body p.card-text");
        aname = cards[i].querySelector(".card-body p.aname");
        if (title.innerText.toUpperCase().indexOf(filter) > -1) {
            cards[i].style.display = "flex";
        } 
        else if (content.innerText.toUpperCase().indexOf(filter) > -1){
          cards[i].style.display = "flex";
        }
        else if (aname.innerText.toUpperCase().indexOf(filter) > -1){
          cards[i].style.display = "flex";
        }
        else {
            cards[i].style.display = "none";
        }
    }
}
</script>
{% endblock %}

Open Blog/project/templates/index.html
{% extends "base.html" %}
<!--Main Context Area-->
{% block content %}
<div class="container">
  <br>
  <div class="card">
    <div class="card-body">
      <center><h2>Publish your passions, your way</h2>
      <em>Create a unique and beautiful blog. It’s easy and free.</em></center>
    </div>
  </div><br>
  
    <div class="row  row-cols-1 row-cols-md-2 g-4" id="tems">
      {% for item in posts %}
      <div class="col">
        <a href="{{ url_for('views.viewpost', p_id = item.post_id) }}">
          <div class="card">
          <div class="img-hover-zoom">
          <img src="../static/image/{{item.coverpic}}" href="#" class="card-img-top" style="z-index: -1;"></div></a>        
          <div class="card-body bg-white" style="z-index:1; margin-top:-100px;">
            <h5 class="card-title ctitle" data-role="search" >{{item.title}}</h5>
            <p class="card-text cont">{{item.content}}</p>
            
            <p class="card-text aname mb-1"><small class="text-muted"><i class="fa fa-user"></i>&nbsp;{{item.aname}}&nbsp;&nbsp;<i class="fa fa-calendar"></i>&nbsp;{{item.post_date}}</small></p>
          

          </div>  
          </div>
        </div>
      
      {%endfor%}
</div></div>
      <div class="rbar">
        <div class="d-flex flex-column flex-shrink-0 p-3 " style="width: 280px;">
      
      
          <h4 style=" margin-bottom:-8px;">Categories</h4>
          <hr style="max-width: 250px;">
      
          <div class="list-group">
            <a href="{{ url_for('views.category',cat = 'Technology') }}" class=" cat-1 list-group-item list-group-item-action d-flex justify-content-between align-items-center" category-one="Technology">Technology
              <span class="badge rounded-pill">14</span>
            </a>
            <a href="{{ url_for('views.category',cat = 'Entertainment') }}" class=" cat-2 list-group-item list-group-item-action d-flex justify-content-between align-items-center" category-one="Entertainment">Entertainment
              <span class="badge rounded-pill">14</span>
            </a>
            <a href="{{ url_for('views.category',cat = 'Sports') }}" class=" cat-3 list-group-item list-group-item-action d-flex justify-content-between align-items-center">Sports
              <span class="badge rounded-pill">14</span>
            </a>
            <a href="{{ url_for('views.category',cat = 'Economy') }}" class=" cat-4 list-group-item list-group-item-action d-flex justify-content-between align-items-center">Economy
              <span class="badge rounded-pill">14</span>
            </a>
            <a href="{{ url_for('views.category',cat = 'Politics') }}" class="cat-5 list-group-item list-group-item-action d-flex justify-content-between align-items-center">Politics
              <span class="badge rounded-pill">14</span>
            </a>
            <a href="{{ url_for('views.category',cat = 'Lifestyle') }}" class="cat-6 list-group-item list-group-item-action d-flex justify-content-between align-items-center">Life Style
              <span class="badge rounded-pill">14</span>
            </a>
            <a href="{{ url_for('views.category',cat = 'Science') }}" class="cat-7 list-group-item list-group-item-action d-flex justify-content-between align-items-center">Science
              <span class="badge rounded-pill">14</span>
            </a>
          </div>
          </div>
        
    
    <h4 style="margin-left:15px; margin-bottom:-8px;">Recommended</h4>
    <hr style="max-width: 250px; margin-left:15px">
  
    {% for item in post %}
    <div class="card mb-3 card-link" style="max-width: 250px; margin-left:15px;">
      <div class="row g-0">
        <div class="col-md-4 row-2">
          <a href="{{ url_for('views.viewpost', p_id = item.post_id) }}">
          <img src="../static/image/{{item.coverpic}}" class="img-fluid rounded-start" alt="...">
        </div></a>
        <div class="col-md-8">
          <div class="card-body">
            <h6 class="card-title ctitle" style="font-size: 13px;">{{item.title}}</h6>
            <p class="card-text cont" style="font-size: 12px;">{{item.content}}</p>
          
          </div>
        </div>
      </div>
    </div>
    {%endfor%}

    </div>
  


<script>
  function search() {
    var input, filter, cards, cardContainer, h5,p, title,content,aname, i;
    input = document.getElementById("searchbar");
    filter = input.value.toUpperCase();
    cardContainer = document.getElementById("tems");
    cards = cardContainer.getElementsByClassName("col");
    for (i = 0; i < cards.length; i++) {
        title = cards[i].querySelector(".card-body h5.card-title");
        content = cards[i].querySelector(".card-body p.card-text");
        aname = cards[i].querySelector(".card-body p.aname");
        if (title.innerText.toUpperCase().indexOf(filter) > -1) {
            cards[i].style.display = "flex";
        } 
        else if (content.innerText.toUpperCase().indexOf(filter) > -1){
          cards[i].style.display = "flex";
        }
        else if (aname.innerText.toUpperCase().indexOf(filter) > -1){
          cards[i].style.display = "flex";
        }
        else {
            cards[i].style.display = "none";
        }
    }
}
</script>
      
{% endblock %}